# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-02 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firetemplate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=30, verbose_name='\u4e3b\u673aHost\u540d\u79f0')),
                ('ip', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('username', models.CharField(max_length=30, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
                ('note', models.TextField(verbose_name='\u5907\u6ce8')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firetemplate.System', verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u914d\u7f6e',
                'verbose_name_plural': '\u4e3b\u673a\u914d\u7f6e',
            },
        ),
    ]
