# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-02 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_message', models.TextField(verbose_name='\u914d\u7f6e\u6a21\u677f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u914d\u7f6e\u6a21\u677f',
                'verbose_name_plural': '\u914d\u7f6e\u6a21\u677f',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=30, verbose_name='\u7cfb\u7edf\u540d')),
                ('system_version', models.CharField(max_length=10, verbose_name='\u7cfb\u7edf\u7248\u672c')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u64cd\u4f5c\u7cfb\u7edf',
                'verbose_name_plural': '\u64cd\u4f5c\u7cfb\u7edf',
            },
        ),
        migrations.AddField(
            model_name='firewalltemplate',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firetemplate.System', verbose_name='\u64cd\u4f5c\u7cfb\u7edf'),
        ),
    ]
