# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-02 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firetemplate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewalltemplate',
            name='template_name',
            field=models.CharField(default='', max_length=30, verbose_name='\u6a21\u677f\u540d'),
        ),
    ]
